### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by IvanMtze** [IvanMtze/Spotify-data#1]
Hacer mockups xD

**Comment by Flor-AC** [comment]
Página de Bienvenida. 

![Bienvenidos](https://user-images.githubusercontent.com/62446269/95376559-e84ebe00-08a6-11eb-9998-61ca400d255e.png)

**Comment by Flor-AC** [comment]
Página para de Iniciar sesión.
![iniciar](https://user-images.githubusercontent.com/62446269/95376685-17652f80-08a7-11eb-90b5-092c56b48572.png)

**Comment by Flor-AC** [comment]
Página de registrar cuenta.
![resgistro_1](https://user-images.githubusercontent.com/62446269/95376735-2946d280-08a7-11eb-8f6f-53afea456e0b.png)
![resgistro_2](https://user-images.githubusercontent.com/62446269/95376743-2b109600-08a7-11eb-8207-a0e061e96e9f.png)

**Comment by Flor-AC** [comment]
Página de contraseña olvidada.
![contraseña](https://user-images.githubusercontent.com/62446269/95376802-424f8380-08a7-11eb-9668-8d81e6a9c584.png)

**Comment by Flor-AC** [comment]
Cuando se ingresan los correos electrónicos la página detecta quien es administrador y cliente. A continuación veremos los dos apartados que puede ver el administrador, puede ver, editar y exportar lo siguiente:

- El número de reproducciones (número de veces que se escucho esa década) que se hicieron en los últimos 30 días.
- El número de escuchados (número de horas que se escucho esa década) que se hicieron en los últimos 30 días.

Lo podemos representar en una gráfica.
![decada](https://user-images.githubusercontent.com/62446269/95377914-cb1aef00-08a8-11eb-9492-99db13c4c123.png)

**Comment by Flor-AC** [comment]
A continuación veremos los dos apartados que puede ver el usuario:

Playlist:
-Se puede observar una tabla con las playlist con un número de popularidad en respectivos países y la fecha en la que se público esta misma.
Artista:
-Se puede observar una tabla determinados artistas con sus canciones más escuchadas, también se puede ver el número de popularidad de esa canción y la fecha de publicación.

![playlist](https://user-images.githubusercontent.com/62446269/95379265-c6573a80-08aa-11eb-9b9c-82651a9dd42f.png)
![artista](https://user-images.githubusercontent.com/62446269/95379258-c48d7700-08aa-11eb-9539-9ce3cbdf1af8.png)

**Comment by IvanMtze** [comment]
Ok flor. Buen trabajo.

**Comment by IvanMtze** [comment]
This makes IvanMtze/Spotify-data#1
