### ISSUE TITLE
PIZARRA-COMENTARIOS VARIOS

### ISSUE THREAD

**Issue by IvanMtze** [IvanMtze/Spotify-data#29]
# Hola chicos. 
Felices fiestas (la neta no se pero todo mundo lo dice y pues no iba a ser el unico idiota sin decirlo). He creado este PR para hacer anotaciones o comentarios y poder enlazarlos más rapido a los commits y eso xD. 
**En unos momentos les estare creando los PR de las funciones/bugs** o lo que sea que haya que agregar. Les asignare a cada uno las tareas pero pus si las quieren cambiar como tarjetas de yu gi oh o lo que quieran, pues namas me dicen y los cambio (no se si se puedan cambiar ustedes mismos. 
Debido al poco tiempo que tenemos para terminar esta madre, creo que la mejor forma de hacerlo es por tareas como les digo xd o si tienen más ideas pues lo hacemos xd. Si ven que me falta algun PR me dicen o lo agregan xd. 
Pues ya, creo que es todo xd. 
Sale (cuando imaginen que les dije "sale")
PD: Que typescript los acompañe y que chrome no les falle.

**Comment by iGusky** [comment]
Muchas gracias :3 espero que se la pasen bien, estaré al pendiente para ver las tareas
