### ISSUE TITLE
No redirección posterior al login

### ISSUE THREAD

**Issue by IvanMtze** [IvanMtze/Spotify-data#35]
Al ingresar correctamente al sistema por medio del login, no se realiza la redirección al url /usr
¿Cómo le hiciste para que te saliera el error?
1. Ingresar al login.
2. Ingresar con una de las cuentas registradas en el sistema
3. Verificar su estado en la consola de desarrollador del navegador.

## Tareas de diseño

* [ ]  N/A

## Tareas de desarrollo

* [ ]  Posible falta de <navigate> o error en el <app-routing>

## Pruebas de comprobacion

* [ ]  @Albert-21

**Comment by iGusky** [comment]
Creo que el error fue solucionado en commits anteriores, ¿podrías revisar si es así en el branch develop?
